export class Books {
    public static books: any = {
        Gen: 'Genesis',
        Exod: 'Exodus',
        Lev: 'Leviticus',
        Num: 'Numbers',
        Deut: 'Deuteronomy',
        Josh: 'Joshua',
        Judg: 'Judges',
        Ruth: 'Ruth',
        '1Sam': '1 Samuel',
        '2Sam': '2 Samuel',
        '1Kgs': '1 Kings',
        '2Kgs': '2 Kings',
        '1Chr': '1 Chronicles',
        '2Chr': '2 Chronicles',
        Ezra: 'Ezra',
        Neh: 'Nehemiah',
        Esth: 'Esther',
        Job: 'Job',
        Ps: 'Psalms',
        Prov: 'Proverbs',
        Eccl: 'Ecclesiastes',
        Song: 'Song of Solomon',
        Isa: 'Isaiah',
        Jer: 'Jeremiah',
        Lam: 'Lamentations',
        Ezek: 'Ezekiel',
        Dan: 'Daniel',
        Hos: 'Hosea',
        Joel: 'Joel',
        Amos: 'Amos',
        Obad: 'Obadiah',
        Jonah: 'Jonah',
        Mic: 'Micah',
        Nah: 'Nahum',
        Hab: 'Habakkuk',
        Zeph: 'Zephaniah',
        Hag: 'Haggai',
        Zech: 'Zechariah',
        Mal: 'Malachi',
        Matt: 'Matthew',
        Mark: 'Mark',
        Luke: 'Luke',
        John: 'John',
        Acts: 'Acts',
        Rom: 'Romans',
        '1Cor': '1 Corinthians',
        '2Cor': '2 Corinthians',
        Gal: 'Galatians',
        Eph: 'Ephesians',
        Phil: 'Philippians',
        Col: 'Colossians',
        '1Thess': '1 Thessalonians',
        '2Thess': '2 Thessalonians',
        '1Tim': '1 Timothy',
        '2Tim': '2 Timothy',
        Titus: 'Titus',
        Phlm: 'Philemon',
        Heb: 'Hebrews',
        Jas: 'James',
        '1Pet': '1 Peter',
        '2Pet': '2 Peter',
        '1John': '1 John',
        '2John': '2 John',
        '3John': '3 John',
        Jude: 'Jude',
        Rev: 'Revelation',
    };

    public static bookOrderMap: any = {
        Genesis: 1,
        Exodus: 2,
        Leviticus: 3,
        Numbers: 4,
        Deuteronomy: 5,
        Joshua: 6,
        Judges: 7,
        Ruth: 8,
        '1 Samuel': 9,
        '2 Samuel': 10,
        '1 Kings': 11,
        '2 Kings': 12,
        '1 Chronicles': 13,
        '2 Chronicles': 14,
        Ezra: 15,
        Nehemiah: 16,
        Esther: 17,
        Job: 18,
        Psalms: 19,
        Proverbs: 20,
        Ecclesiastes: 21,
        'Song of Solomon': 22,
        Isaiah: 23,
        Jeremiah: 24,
        Lamentations: 25,
        Ezekiel: 26,
        Daniel: 27,
        Hosea: 28,
        Joel: 29,
        Amos: 30,
        Obadiah: 31,
        Jonah: 32,
        Micah: 33,
        Nahum: 34,
        Habakkuk: 35,
        Zephaniah: 36,
        Haggai: 37,
        Zechariah: 38,
        Malachi: 39,
        Matthew: 40,
        Mark: 41,
        Luke: 42,
        John: 43,
        Acts: 44,
        Romans: 45,
        '1 Corinthians': 46,
        '2 Corinthians': 47,
        Galatians: 48,
        Ephesians: 49,
        Philippians: 50,
        Colossians: 51,
        '1 Thessalonians': 52,
        '2 Thessalonians': 53,
        '1 Timothy': 54,
        '2 Timothy': 55,
        Titus: 56,
        Philemon: 57,
        Hebrews: 58,
        James: 59,
        '1 Peter': 60,
        '2 Peter': 61,
        '1 John': 62,
        '2 John': 63,
        '3 John': 64,
        Jude: 65,
        Revelation: 66,
    };
}
